module.exports = {
    // Not found
    NOT_FOUND: { errorCode: 1000, httpCode: 404, message: 'NOT_FOUND' },
    SPACE_NOT_FOUND: { errorCode: 1001, httpCode: 404, message: 'SPACE_NOT_FOUND' },
    TOOL_NOT_FOUND: { errorCode: 1002, httpCode: 404, message: 'TOOL_NOT_FOUND' },
    TOOL_MODEL_NOT_FOUND: { errorCode: 1003, httpCode: 404, message: 'TOOL_MODEL_NOT_FOUND' },
    SPACE_MODEL_NOT_FOUND: { errorCode: 1004, httpCode: 404, message: 'SPACE_MODEL_NOT_FOUND' },
    SENSOR_MEASURE_NOT_FOUND: { errorCode: 1005, httpCode: 404, message: 'SENSOR_MEASURE_NOT_FOUND' },
    COMPANY_NOT_FOUND: { errorCode: 1006, httpCode: 404, message: 'COMPANY_NOT_FOUND' },
    CONTACT_PET_NOT_FOUND: { errorCode: 1007, httpCode: 404, message: 'CONTACT_PET_NOT_FOUND' },
    ALERT_NOT_FOUND: { errorCode: 1008, httpCode: 404, message: 'ALERT_NOT_FOUND' },
    ALERT_LOG_NOT_FOUND: { errorCode: 1009, httpCode: 404, message: 'ALERT_LOG_NOT_FOUND' },
    CONTACT_NOT_FOUND: { errorCode: 1010, httpCode: 404, message: 'CONTACT_NOT_FOUND' },
    CONTACT_LIST_NOT_FOUND: { errorCode: 1011, httpCode: 404, message: 'CONTACT_LIST_NOT_FOUND' },
    ZONE_NOT_FOUND: { errorCode: 1011, httpCode: 404, message: 'ZONE_NOT_FOUND' },
    IMAGE_NOT_FOUND: { errorCode: 1012, httpCode: 404, message: 'IMAGE_NOT_FOUND' },
    SENSOR_MODEL_NOT_FOUND: { errorCode: 1013, httpCode: 404, message: 'SENSOR_MODEL_NOT_FOUND' },
    DETECTOR_NOT_FOUND: { errorCode: 1014, httpCode: 404, message: 'DETECTOR_NOT_FOUND' },
    PLANT_NOT_FOUND: { errorCode: 1015, httpCode: 404, message: 'PLANT_NOT_FOUND' },
    IPE_NOT_FOUND: { errorCode: 1016, httpCode: 404, message: 'IPE_NOT_FOUND' },
    IPE_MODEL_NOT_FOUND: { errorCode: 1017, httpCode: 404, message: 'IPE_MODEL_NOT_FOUND' },
    PET_NOT_FOUND: { errorCode: 1018, httpCode: 404, message: 'PET_NOT_FOUND' },
    RISK_CHECK_NOT_FOUND: { errorCode: 1019, httpCode: 404, message: 'RISK_CHECK_NOT_FOUND' },
    PET_CERTIFICATE_NOT_FOUND: {
        errorCode: 1019,
        httpCode: 404,
        message: 'PET_CERTIFICATE_NOT_FOUND',
    },
    PET_IPE_NOT_FOUND: { errorCode: 1019, httpCode: 404, message: 'PET_IPE_NOT_FOUND' },
    PET_TOOL_NOT_FOUND: { errorCode: 1019, httpCode: 404, message: 'PET_TOOL_NOT_FOUND' },
    CAMERA_NOT_FOUND: { errorCode: 1020, httpCode: 404, message: 'CAMERA_NOT_FOUND' },
    ANTENNA_NOT_FOUND: { errorCode: 1021, httpCode: 404, message: 'ANTENNA_NOT_FOUND' },
    PROCEDURE_NOT_FOUND: { errorCode: 1022, httpCode: 404, message: 'PROCEDURE_NOT_FOUND' },
    CERTIFICATE_NOT_FOUND: { errorCode: 1023, httpCode: 404, message: 'CERTIFICATE_NOT_FOUND' },
    CONTACT_CERTIFICATE_NOT_FOUND: {
        errorCode: 1024,
        httpCode: 404,
        message: 'CONTACT_CERTIFICATE_NOT_FOUND',
    },
    SPACE_RISK_NOT_FOUND: { errorCode: 1024, httpCode: 404, message: 'SPACE_RISK_NOT_FOUND' },
    RISK_NOT_FOUND: { errorCode: 1025, httpCode: 404, message: 'RISK_NOT_FOUND' },
    MEDICAL_EXAM_NOT_FOUND: { errorCode: 1026, httpCode: 404, message: 'MEDICAL_EXAM_NOT_FOUND' },
    CONTACT_MEDICAL_EXAM_NOT_FOUND: {
        errorCode: 1027,
        httpCode: 404,
        message: 'CONTACT_MEDICAL_EXAM_NOT_FOUND',
    },
    PET_MEDICAL_EXAM_NOT_FOUND: {
        errorCode: 1028,
        httpCode: 404,
        message: 'PET_MEDICAL_EXAM_NOT_FOUND',
    },
    RFID_LOG_NOT_FOUND: { errorCode: 1029, httpCode: 404, message: 'RFID_LOG_NOT_FOUND' },
    SPACE_PROCEDURE_NOT_FOUND: { errorCode: 1030, httpCode: 404, message: 'SPACE_PROCEDURE_NOT_FOUND' },
    LICENSE_NOT_FOUND: { errorCode: 1031, httpCode: 404, message: 'LICENSE_NOT_FOUND' },
    // Could not create
    COULD_NOT_CREATE: { errorCode: 2000, httpCode: 500, message: 'COULD_NOT_CREATE' },
    COULD_NOT_CREATE_TOOL: { errorCode: 2001, httpCode: 500, message: 'COULD_NOT_CREATE_TOOL' },
    COULD_NOT_CREATE_TOOL_MODEL: {
        errorCode: 2002,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_TOOL_MODEL',
    },
    COULD_NOT_CREATE_ALERT_LOG: {
        errorCode: 2003,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_ALERT_LOG',
    },
    COULD_NOT_CREATE_ALERT: { errorCode: 2004, httpCode: 500, message: 'COULD_NOT_CREATE_ALERT' },
    COULD_NOT_CREATE_SENSOR_MEASURE: {
        errorCode: 2005,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_SENSOR_MEASURE',
    },
    COULD_NOT_CREATE_CONTACT_PET: {
        errorCode: 2006,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_CONTACT_PET',
    },
    COULD_NOT_CREATE_SENSOR_MODEL: {
        errorCode: 2007,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_SENSOR_MODEL',
    },
    COULD_NOT_CREATE_DETECTOR: { errorCode: 2008, httpCode: 500, message: 'COULD_NOT_CREATE_DETECTOR' },
    COULD_NOT_CREATE_COMPANY: { errorCode: 2009, httpCode: 500, message: 'COULD_NOT_CREATE_COMPANY' },
    COULD_NOT_CREATE_SPACE_MODEL: {
        errorCode: 2010,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_SPACE_MODEL',
    },
    COULD_NOT_CREATE_SPACE: { errorCode: 2011, httpCode: 500, message: 'COULD_NOT_CREATE_SPACE' },
    COULD_NOT_CREATE_CONTACT: { errorCode: 2012, httpCode: 500, message: 'COULD_NOT_CREATE_CONTACT' },
    COULD_NOT_CREATE_CONTACT_PLANT: {
        errorCode: 2013,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_CONTACT_PLANT',
    },
    COULD_NOT_CREATE_ZONE: { errorCode: 2014, httpCode: 500, message: 'COULD_NOT_CREATE_ZONE' },
    COULD_NOT_CREATE_PLANT: { errorCode: 2015, httpCode: 500, message: 'COULD_NOT_CREATE_PLANT' },
    COULD_NOT_CREATE_PET: { errorCode: 2016, httpCode: 500, message: 'COULD_NOT_CREATE_PET' },
    COULD_NOT_CREATE_FOLDER: { errorCode: 2017, httpCode: 500, message: 'COULD_NOT_CREATE_FOLDER' },
    COULD_NOT_CREATE_IMAGE: { errorCode: 2018, httpCode: 500, message: 'COULD_NOT_CREATE_IMAGE' },
    COULD_NOT_CREATE_IPE: { errorCode: 2019, httpCode: 500, message: 'COULD_NOT_CREATE_IPE' },
    COULD_NOT_CREATE_IPE_MODEL: {
        errorCode: 2020,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_IPE_MODEL',
    },
    COULD_NOT_CREATE_RISK_CHECK: {
        errorCode: 2021,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_RISK_CHECK',
    },
    COULD_NOT_CREATE_PET_CERTIFICATE: {
        errorCode: 2021,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_PET_CERTIFICATE',
    },
    COULD_NOT_CREATE_PET_IPE: { errorCode: 2021, httpCode: 500, message: 'COULD_NOT_CREATE_PET_IPE' },
    COULD_NOT_CREATE_PET_TOOL: {
        errorCode: 2021,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_PET_TOOL',
    },
    COULD_NOT_CREATE_CAMERA: { errorCode: 2022, httpCode: 500, message: 'COULD_NOT_CREATE_CAMERA' },
    COULD_NOT_CREATE_ANTENNA: { errorCode: 2023, httpCode: 500, message: 'COULD_NOT_CREATE_ANTENNA' },
    COULD_NOT_CREATE_CERTIFICATE: {
        errorCode: 2024,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_CERTIFICATE',
    },
    COULD_NOT_CREATE_PROCEDURE: {
        errorCode: 2025,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_PROCEDURE',
    },
    COULD_NOT_CREATE_CONTACT_CERTIFICATE: {
        errorCode: 2025,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_CONTACT_CERTIFICATE',
    },
    COULD_NOT_CREATE_SPACE_IPEMODEL: {
        errorCode: 2026,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_SPACE_IPEMODEL',
    },
    COULD_NOT_CREATE_SPACE_RISK: {
        errorCode: 2027,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_SPACE_RISK',
    },
    COULD_NOT_CREATE_RISK: {
        errorCode: 2028,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_RISK',
    },
    COULD_NOT_CREATE_MEDICAL_EXAM: {
        errorCode: 2029,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_MEDICAL_EXAM',
    },
    COULD_NOT_CREATE_CONTACT_MEDICAL_EXAM: {
        errorCode: 2030,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_CONTACT_MEDICAL_EXAM',
    },
    COULD_NOT_CREATE_PET_MEDICAL_EXAM: {
        errorCode: 2031,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_PET_MEDICAL_EXAM',
    },
    COULD_NOT_CREATE_SPACE_PROCEDURE: {
        errorCode: 2032,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_SPACE_PROCEDURE',
    },
    COULD_NOT_CREATE_CONTACT_IPE: {
        errorCode: 2033,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_CONTACT_IPE',
    },
    COULD_NOT_CREATE_LICENSE: {
        errorCode: 2034,
        httpCode: 500,
        message: 'COULD_NOT_CREATE_LICENSE'
    },
    // Could not update
    COULD_NOT_UPDATE: { errorCode: 3000, httpCode: 500, message: 'COULD_NOT_UPDATE' },
    COULD_NOT_UPDATE_TOOL: { errorCode: 3001, httpCode: 500, message: 'COULD_NOT_UPDATE_TOOL' },
    COULD_NOT_UPDATE_TOOL_MODEL: {
        errorCode: 3002,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_TOOL_MODEL',
    },
    COULD_NOT_UPDATE_ALERT_LOG: {
        errorCode: 3003,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_ALERT_LOG',
    },
    COULD_NOT_UPDATE_ALERT: { errorCode: 3004, httpCode: 500, message: 'COULD_NOT_UPDATE_ALERT' },
    COULD_NOT_UPDATE_SENSOR_MEASURE: {
        errorCode: 3005,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_SENSOR_MEASURE',
    },
    COULD_NOT_UPDATE_CONTACT_PET: {
        errorCode: 3006,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_CONTACT_PET',
    },
    COULD_NOT_UPDATE_SENSOR_MODEL: {
        errorCode: 3007,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_SENSOR_MODEL',
    },
    COULD_NOT_UPDATE_DETECTOR: { errorCode: 3008, httpCode: 500, message: 'COULD_NOT_UPDATE_DETECTOR' },
    COULD_NOT_UPDATE_COMPANY: { errorCode: 3009, httpCode: 500, message: 'COULD_NOT_UPDATE_COMPANY' },
    COULD_NOT_UPDATE_SPACE_MODEL: {
        errorCode: 3010,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_SPACE_MODEL',
    },
    COULD_NOT_UPDATE_SPACE: { errorCode: 3011, httpCode: 500, message: 'COULD_NOT_UPDATE_SPACE' },
    COULD_NOT_UPDATE_CONTACT: { errorCode: 3012, httpCode: 500, message: 'COULD_NOT_UPDATE_CONTACT' },
    COULD_NOT_UPDATE_CONTACT_PLANT: {
        errorCode: 3013,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_CONTACT_PLANT',
    },
    COULD_NOT_UPDATE_ZONE: { errorCode: 3014, httpCode: 500, message: 'COULD_NOT_UPDATE_ZONE' },
    COULD_NOT_UPDATE_PLANT: { errorCode: 3015, httpCode: 500, message: 'COULD_NOT_UPDATE_PLANT' },
    COULD_NOT_UPDATE_IPE: { errorCode: 3016, httpCode: 500, message: 'COULD_NOT_UPDATE_IPE' },
    COULD_NOT_UPDATE_IPE_MODEL: {
        errorCode: 3017,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_IPE_MODEL',
    },
    COULD_NOT_UPDATE_PET: { errorCode: 3018, httpCode: 500, message: 'COULD_NOT_UPDATE_PET' },
    COULD_NOT_UPDATE_RISK_CHECK: {
        errorCode: 3019,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_RISK_CHECK',
    },
    COULD_NOT_UPDATE_PET_CERTIFICATE: {
        errorCode: 3019,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_PET_CERTIFICATE',
    },
    COULD_NOT_UPDATE_PET_IPE: { errorCode: 3019, httpCode: 500, message: 'COULD_NOT_UPDATE_PET_IPE' },
    COULD_NOT_UPDATE_PET_TOOL: {
        errorCode: 3019,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_PET_TOOL',
    },
    COULD_NOT_UPDATE_CAMERA: { errorCode: 3020, httpCode: 500, message: 'COULD_NOT_UPDATE_CAMERA' },
    COULD_NOT_UPDATE_ANTENNA: { errorCode: 3021, httpCode: 500, message: 'COULD_NOT_UPDATE_ANTENNA' },
    COULD_NOT_UPDATE_CERTIFICATE: {
        errorCode: 3022,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_CERTIFICATE',
    },
    COULD_NOT_UPDATE_PROCEDURE: {
        errorCode: 3023,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_PROCEDURE',
    },
    COULD_NOT_UPDATE_CONTACT_CERTIFICATE: {
        errorCode: 3024,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_CONTACT_CERTIFICATE',
    },
    COULD_NOT_UPDATE_SPACE_IPEMODEL: {
        errorCode: 3025,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_SPACE_IPEMODEL',
    },
    COULD_NOT_UPDATE_SPACE_RISK: {
        errorCode: 3026,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_SPACE_RISK',
    },
    COULD_NOT_UPDATE_RISK: {
        errorCode: 3027,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_RISK',
    },
    COULD_NOT_UPDATE_MEDICAL_EXAM: {
        errorCode: 3028,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_MEDICAL_EXAM',
    },
    COULD_NOT_UPDATE_CONTACT_MEDICAL_EXAM: {
        errorCode: 3029,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_CONTACT_MEDICAL_EXAM',
    },
    COULD_NOT_UPDATE_PET_MEDICAL_EXAM: {
        errorCode: 3030,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_PET_MEDICAL_EXAM',
    },
    COULD_NOT_UPDATE_SPACE_PROCEDURE: {
        errorCode: 3031,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_SPACE_PROCEDURE',
    },
    COULD_NOT_UPDATE_LICENSE: {
        errorCode: 3032,
        httpCode: 500,
        message: 'COULD_NOT_UPDATE_LICENSE'
    },

    // Could not delete
    COULD_NOT_DELETE: { errorCode: 4000, httpCode: 500, message: 'COULD_NOT_DELETE' },
    COULD_NOT_DELETE_TOOL: { errorCode: 4001, httpCode: 500, message: 'COULD_NOT_DELETE_TOOL' },
    COULD_NOT_DELETE_TOOL_MODEL: {
        errorCode: 4002,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_TOOL_MODEL',
    },
    COULD_NOT_DELETE_ALERT_LOG: {
        errorCode: 4003,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_ALERT_LOG',
    },
    COULD_NOT_DELETE_ALERT: { errorCode: 4004, httpCode: 500, message: 'COULD_NOT_DELETE_ALERT' },
    COULD_NOT_DELETE_SENSOR_MEASURE: {
        errorCode: 4005,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_SENSOR_MEASURE',
    },
    COULD_NOT_DELETE_CONTACT_PET: {
        errorCode: 4006,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_CONTACT_PET',
    },
    COULD_NOT_DELETE_SENSOR_MODEL: {
        errorCode: 4007,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_SENSOR_MODEL',
    },
    COULD_NOT_DELETE_DETECTOR: { errorCode: 4008, httpCode: 500, message: 'COULD_NOT_DELETE_DETECTOR' },
    COULD_NOT_DELETE_COMPANY: { errorCode: 4009, httpCode: 500, message: 'COULD_NOT_DELETE_COMPANY' },
    COULD_NOT_DELETE_SPACE_MODEL: {
        errorCode: 4010,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_SPACE_MODEL',
    },
    COULD_NOT_DELETE_SPACE: { errorCode: 4011, httpCode: 500, message: 'COULD_NOT_DELETE_SPACE' },
    COULD_NOT_DELETE_CONTACT: { errorCode: 4012, httpCode: 500, message: 'COULD_NOT_DELETE_CONTACT' },
    COULD_NOT_DELETE_CONTACT_PLANT: {
        errorCode: 4013,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_CONTACT_PLANT',
    },
    COULD_NOT_DELETE_ZONE: { errorCode: 4014, httpCode: 500, message: 'COULD_NOT_DELETE_ZONE' },
    COULD_NOT_DELETE_PLANT: { errorCode: 4015, httpCode: 500, message: 'COULD_NOT_DELETE_PLANT' },
    COULD_NOT_DELETE_PET: { errorCode: 4016, httpCode: 500, message: 'COULD_NOT_DELETE_PET' },
    COULD_NOT_DELETE_TOOL_MODEL_BECAUSE_TOOL: {
        errorCode: 4017,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_TOOL_MODEL_BECAUSE_TOOL',
    },
    COULD_NOT_DELETE_PET_BECAUSE_RISK_CHECK: {
        errorCode: 4018,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_PET_BECAUSE_RISK_CHECK',
    },
    COULD_NOT_DELETE_PET_BECAUSE_CONTACT_PET: {
        errorCode: 4019,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_PET_BECAUSE_CONTACT_PET',
    },
    COULD_NOT_DELETE_ALERT_BECAUSE_ALERT_LOG: {
        errorCode: 4020,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_ALERT_BECAUSE_ALERT_LOG',
    },
    COULD_NOT_DELETE_COMPANY_BECAUSE_ZONE: {
        errorCode: 4021,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_COMPANY_BECAUSE_ZONE',
    },
    COULD_NOT_DELETE_COMPANY_BECAUSE_CONTACT: {
        errorCode: 4022,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_COMPANY_BECAUSE_CONTACT',
    },
    COULD_NOT_DELETE_SENSOR_MODEL_BECAUSE_SENSOR: {
        errorCode: 4023,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_SENSOR_MODEL_BECAUSE_SENSOR',
    },
    COULD_NOT_DELETE_SENSOR_BECAUSE_ALERT_LOG: {
        errorCode: 4024,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_SENSOR_BECAUSE_ALERT_LOG',
    },
    COULD_NOT_DELETE_SPACE_MODEL_BECAUSE_SPACE: {
        errorCode: 4025,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_SPACE_MODEL_BECAUSE_SPACE',
    },
    COULD_NOT_DELETE_CONTACT_BECAUSE_ALERT: {
        errorCode: 4026,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_CONTACT_BECAUSE_ALERT',
    },
    COULD_NOT_DELETE_PLANT_BECAUSE_SPACE: {
        errorCode: 4027,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_PLANT_BECAUSE_SPACE',
    },
    COULD_NOT_DELETE_ZONE_BECAUSE_PLANT: {
        errorCode: 4028,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_ZONE_BECAUSE_PLANT',
    },
    COULD_NOT_DELETE_SPACE_BECAUSE_ALERT: {
        errorCode: 4029,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_SPACE_BECAUSE_ALERT',
    },
    COULD_NOT_DELETE_SPACE_BECAUSE_SENSOR: {
        errorCode: 4030,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_SPACE_BECAUSE_SENSOR',
    },
    COULD_NOT_DELETE_SPACE_BECAUSE_PET: {
        errorCode: 4031,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_SPACE_BECAUSE_PET',
    },
    COULD_NOT_DELETE_PET_BECAUSE_SENSOR_MEASURE: {
        errorCode: 4032,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_PET_BECAUSE_SENSOR_MEASURE',
    },
    COULD_NOT_DELETE_RISK_CHECK: {
        errorCode: 4033,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_RISK_CHECK',
    },
    COULD_NOT_DELETE_IPE: { errorCode: 4034, httpCode: 500, message: 'COULD_NOT_DELETE_IPE' },
    COULD_NOT_DELETE_IPE_MODEL: {
        errorCode: 4035,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_IPE_MODEL',
    },
    COULD_NOT_DELETE_IPE_MODEL_BECAUSE_IPE: {
        errorCode: 4036,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_IPE_MODEL_BECAUSE_IPE',
    },
    COULD_NOT_DELETE_PET_CERTIFICATE: {
        errorCode: 4037,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_PET_CERTIFICATE',
    },
    COULD_NOT_DELETE_PET_IPE: { errorCode: 4038, httpCode: 500, message: 'COULD_NOT_DELETE_PET_IPE' },
    COULD_NOT_DELETE_PET_TOOL: {
        errorCode: 4039,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_PET_TOOL',
    },
    COULD_NOT_DELETE_PET_BECAUSE_PET_CERTIFICATE: {
        errorCode: 4040,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_PET_BECAUSE_PET_CERTIFICATE',
    },
    COULD_NOT_DELETE_PET_BECAUSE_PET_IPE: {
        errorCode: 4041,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_PET_BECAUSE_PET_IPE',
    },
    COULD_NOT_DELETE_PET_BECAUSE_PET_TOOL: {
        errorCode: 4042,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_PET_BECAUSE_PET_TOOL',
    },
    COULD_NOT_DELETE_CAMERA: { errorCode: 4043, httpCode: 500, message: 'COULD_NOT_DELETE_CAMERA' },
    COULD_NOT_DELETE_ANTENNA: { errorCode: 4044, httpCode: 500, message: 'COULD_NOT_DELETE_ANTENNA' },
    COULD_NOT_DELETE_CERTIFICATE: {
        errorCode: 4045,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_CERTIFICATE',
    },
    COULD_NOT_DELETE_PROCEDURE: {
        errorCode: 4046,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_PROCEDURE',
    },
    COULD_NOT_DELETE_CONTACT_CERTIFICATE: {
        errorCode: 4047,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_CONTACT_CERTIFICATE',
    },
    COULD_NOT_DELETE_SPACE_IPEMODEL: {
        errorCode: 4048,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_SPACE_IPEMODEL',
    },
    COULD_NOT_DELETE_SPACE_RISK: {
        errorCode: 4011,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_SPACE_RISK',
    },
    COULD_NOT_DELETE_RISK: {
        errorCode: 4049,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_RISK',
    },
    COULD_NOT_DELETE_MEDICAL_EXAM: {
        errorCode: 4050,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_MEDICAL_EXAM',
    },
    COULD_NOT_DELETE_CONTACT_MEDICAL_EXAM: {
        errorCode: 4051,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_CONTACT_MEDICAL_EXAM',
    },
    COULD_NOT_DELETE_PET_MEDICAL_EXAM: {
        errorCode: 4052,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_PET_MEDICAL_EXAM',
    },
    COULD_NOT_DELETE_SPACE_PROCEDURE: {
        errorCode: 4053,
        httpCode: 500,
        message: 'COULD_NOT_DELETE_SPACE_PROCEDURE',
    },
    COULD_NOT_DELETE_LICENSE: { errorCode: 4054, httpCode: 500, message: 'COULD_NOT_DELETE_LICENSE' },

    // Wrong parameters errors
    WRONG_PARAMETERS: { errorCode: 5000, httpCode: 400, message: 'WRONG_PARAMETERS' },
    WRONG_PARAMETERS_DATES_INCONSISTENT: {
        errorCode: 5001,
        httpCode: 400,
        message: 'WRONG_PARAMETERS_DATES_INCONSISTENT',
    },

    // Empty list
    EMPTY_LIST: { errorCode: 6000, httpCode: 500, message: 'EMPTY_LIST' },

    // Already Exists
    ALREADY_EXISTS: { errorCode: 7000, httpCode: 500, message: 'ALREADY_EXISTS' },
    COMPANY_CODE_ALREADY_EXISTS: {
        errorCode: 7001,
        httpCode: 500,
        message: 'COMPANY_CODE_ALREADY_EXISTS',
    },
    SERIAL_NUMBER_ALREADY_EXISTS: {
        errorCode: 7002,
        httpCode: 500,
        message: 'SERIAL_NUMBER_ALREADY_EXISTS',
    },
    USERNAME_ALREADY_EXISTS: { errorCode: 7003, httpCode: 500, message: 'USERNAME_ALREADY_EXISTS' },
    ACTIVE_PET_IN_SPACE_ALREADY_EXISTS: {
        errorCode: 7004,
        httpCode: 409,
        message: 'ACTIVE_PET_IN_SPACE_ALREADY_EXISTS',
    },
    EMAIL_ALREADY_EXISTS: { errorCode: 7005, httpCode: 500, message: 'EMAIL_ALREADY_EXISTS' },
    REGISTRATION_ALREADY_EXISTS: { errorCode: 7006, httpCode: 500, message: 'REGISTRATION_ALREADY_EXISTS' },

    // Failed
    FAILED_TO_AUTHENTICATE: { errorCode: 8000, httpCode: 401, message: 'FAILED_TO_AUTHENTICATE' },
    FAILED_TO_SEND_EMAIL: { errorCode: 8001, httpCode: 500, message: 'FAILED_TO_SEND_EMAIL' },
    FAILED_TO_LOGIN: { errorCode: 8002, httpCode: 404, message: 'FAILED_TO_LOGIN' },
    TOO_MANY_REQUESTS: { errorCode: 8003, httpCode: 429, message: 'TOO_MANY_REQUESTS' },
    FAILED_TO_OPEN_SOCKET: { errorCode: 8004, httpCode: 500, message: 'FAILED_TO_OPEN_SOCKET' },
    FAILED_TO_CLOSE_SOCKET: { errorCode: 8005, httpCode: 500, message: 'FAILED_TO_CLOSE_SOCKET' },
    FAILED_TO_SYNC_AUTOMATION: {
        errorCode: 8006,
        httpCode: 404,
        message: 'FAILED_TO_SYNC_AUTOMATION',
    },
    ACCOUNT_LOCKED: { errorCode: 8007, httpCode: 404, message: 'ACCOUNT_LOCKED' },
    RECORD_FAILED: { errorCode: 8008, httpCode: 404, message: 'FAILED_TO_RECORD_SESSION' },
};
